# Generated by Django 4.1.6 on 2023-02-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('marks', models.FloatField()),
            ],
        ),
    ]
